#! /usr/bin/python

import DMPSW
import libDmpSvcDatabase as Database
import libDmpAlgtestDatabase as TestDatabase

DMPSW.Core.Set("EventNumber","10")

gDatabaseSvc = Database.DmpSvcDatabase.GetInstance()
gDatabaseSvc.Set("Package","Calibration")
gDatabaseSvc.Set("Pedestal/Read","Ped0903")
#database.Set("Update","tmpPed")
DMPSW.SvcMgr.Append(gDatabaseSvc)
#gDatabaseSvc.Initialize()
#gDatabaseSvc.Finalize()

testDatabase = TestDatabase.DmpAlgtestDatabase()
DMPSW.AlgMgr.Append(testDatabase)

DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

